"""End-to-end: real ACME client -> acme-lan -> Pebble upstream (DNS-01) -> valid cert.

This is the headline test. It proves the whole proxy: an internal client obtains a
certificate from acme-lan, which in turn obtains it from a real (test) CA via DNS-01,
forwarding the client's own CSR so the issued leaf matches the client's key.
"""

from __future__ import annotations

from cryptography import x509
from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat
from cryptography.x509.oid import ExtensionOID

from ..conftest import make_csr
from ..downstream import answer_http01_challenges, build_downstream_client


def _leaf_public_key_bytes(pubkey) -> bytes:
    return pubkey.public_bytes(Encoding.DER, PublicFormat.SubjectPublicKeyInfo)


def test_full_issuance_via_pebble(make_server, pebble, challenge_responder, tmp_path):
    base = make_server(
        ACME_LAN_UPSTREAM_DIRECTORY_URL=pebble["directory"],
        ACME_LAN_UPSTREAM_VERIFY_SSL="false",
        ACME_LAN_DNS_PROVIDER="challtestsrv",
        ACME_LAN_CHALLTESTSRV_URL=pebble["challtestsrv"],
        ACME_LAN_UPSTREAM_ACCOUNT_KEY_PATH=str(tmp_path / "upstream_account.key"),
        ACME_LAN_UPSTREAM_FINALIZE_TIMEOUT="90",
    )

    acme_client, account_key = build_downstream_client(base)

    domain = "db.lan.test"
    csr_pem, client_key = make_csr([domain])
    csr = x509.load_pem_x509_csr(csr_pem)

    orderr = acme_client.new_order(csr_pem)
    answer_http01_challenges(acme_client, account_key, orderr, challenge_responder)

    finalized = acme_client.poll_and_finalize(orderr)

    # We received a real chain from the upstream CA.
    chain = x509.load_pem_x509_certificates(finalized.fullchain_pem.encode())
    assert len(chain) >= 2, "expected leaf + at least one issuer"
    leaf = chain[0]

    # The leaf covers the requested identifier.
    san = leaf.extensions.get_extension_for_oid(ExtensionOID.SUBJECT_ALTERNATIVE_NAME)
    assert domain in san.value.get_values_for_type(x509.DNSName)

    # Critical correctness check: the leaf was issued for the CLIENT's key (CSR forwarding),
    # not some key generated by acme-lan.
    assert _leaf_public_key_bytes(leaf.public_key()) == _leaf_public_key_bytes(
        csr.public_key()
    )
    assert _leaf_public_key_bytes(leaf.public_key()) == _leaf_public_key_bytes(
        client_key.public_key()
    )

    # The issuer is Pebble, not acme-lan.
    assert "Pebble" in leaf.issuer.rfc4514_string() or leaf.issuer != leaf.subject
